fix: workaround android 7 crash with Hex.encodeHexString
For some reason it keeps trying to use the system apache commons instead
of the one in the app, and because that one is really old, this method
is missing so it crashes.

Crash report
 - Time: 26-Dec-2025 6:46:49 PM
 - Device: lineage_Hol-U19 Hol-U19
 - Android version: 7.1.2
 - Crash stack trace:
 - Launcher version:
amethyst-legacy-20251226-c798f65-feat/import-modpack
java.lang.NoSuchMethodError: No static method
encodeHexString([B)Ljava/lang/String; in class
Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration
of 'org.apache.commons.codec.binary.Hex' appears in
/system/framework/org.apache.http.legacy.boot.jar)